apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.mongodb.type }}
data: 
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.database }}
  MONGODB_URI: {{ .Values.mongodb.uri }}
  SESSION_SECRET: {{ .Values.mongodb.secret }}
  EMAIL_USER: {{ .Values.mongodb.email }}
  EMAIL_PASS: {{ .Values.mongodb.password }}
  PORT: {{ .Values.userprofile.port | quote }}
